params:
  seed: 42

  env:
    clip_observations: 5.0
    clip_actions: 1.0

  algo:
    name: ppo

  model:
    name: continuous_ppo

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [64, 64]
      activation: relu

  load_checkpoint: False
  load_path: ''

  config:
    name: surgery_needle_ppo
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    num_actors: -1
    gamma: 0.99
    tau : 0.95
    learning_rate: 3e-4
    max_epochs: 100
    save_frequency: 25
    grad_norm: 0.5
    entropy_coef: 0.0
    horizon_length: 64
    minibatch_size: 8192
    mini_epochs: 4
    critic_coef: 1.0
    clip_value: True
    seq_length: 4
